site_name: Execution Flows
theme:
    name: material
    features:
      - search.suggest
      - search.highlight
      - toc.integrate
      - navigation.footer
      - content.code.copy
    icon:
        repo: fontawesome/brands/github
        logo: fontawesome/brands/pied-piper-alt
    palette:
        - scheme: slate
          toggle:
            icon: material/brightness-7
            name: Switch to light mode
          primary: teal
          accent: purple
        - scheme: default
          toggle:
            icon: material/brightness-3
            name: Switch to dark mode
          primary: indigo
          accent: purple
    language: en
    font:
        text: JetBrains Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true

repo_url: https://github.com/execution-flows/fy
repo_name: execution-flows/fy

# Order of pages
nav:
  - Home: index.md
  - Tutorial:
      - Flow: tutorial/flow.md
      - Flow Using Property: tutorial/flow_using_property.md
      - Flow Using Method: tutorial/flow_using_method.md
  - Reference:
      - Flow: reference/flow.md
      - Property:
        - Property & Abstract Property: reference/Property/property
        - Usage in Execution Flow: reference/Property/property_in_flow
      - Method: reference/method.md
