site_name: 'Execution Flows'
theme:
    name: material
    favicon: ef-logo.svg
    features:
      - search.suggest
      - search.highlight
      - navigation.footer
      - navigation.top
      - content.code.copy
    icon:
        repo: fontawesome/brands/github
    logo: ef-logo.svg
    palette:
        - scheme: slate
          toggle:
            icon: material/brightness-7
            name: Switch to light mode
          primary: teal
          accent: purple
        - scheme: default
          toggle:
            icon: material/brightness-3
            name: Switch to dark mode
          primary: indigo
          accent: purple
    language: en
    font:
        text: JetBrains Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true

repo_url: https://github.com/execution-flows/fy
repo_name: execution-flows/fy

# Order of pages
nav:
  - Introduction: index.md
  - Getting Started:
      - Installation and setup: getting_started/installation.md
      - Project Structure: getting_started/project_structure.md
  - Tutorial:
      - Flow:
        - What is Flow: tutorial/flow/flow.md
      - Property:
        - What are properties: tutorial/property/property.md
        - Including a Property in a Flow: tutorial/property/property_in_flow.md
        - Property with Property: tutorial/property/property_with_property.md
        - What are Property Setters: tutorial/property/setters.md
      - Method:
        - Method: tutorial/method/method.md
        - Including a Method in a Flow: tutorial/method/flow_includes_method.md
        - Properties in Methods: tutorial/method/methods_using_properties.md
