[tool.poetry]
name = "fy_library"
version = "0.2.14-dev"
description = "Implementation of fy tool functionality - parsing and generating."
authors = ["Vinko Buble <vinkobuble@gmail.com>","Jere Perisic <jereperisic@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

jinja2 = "3.1.4"
pydantic = "2.8.2"

fy-core = { path = "../core", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py310"]
