name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      FY_VERSION:
        type: string
        description: fy tool version to publish
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        shell: bash
        run: pipx install poetry

      - name: Config PyPI API Token
        shell: bash
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: [library] Set fy-core version
        working-directory: library
        shell: bash
        run: poetry version "${{ inputs.FY_VERSION }}"

      - name: [cli] Set fy-core version
        working-directory: cli
        shell: bash
        run: poetry version "${{ inputs.FY_VERSION }}"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "v${{ inputs.FY_VERSION }}"
          tags: true

      - name: [library] Set fy-core version
        working-directory: library
        shell: bash
        run: poetry add fy-core==0.1.0

      - name: [library] Install dependencies
        working-directory: library
        shell: bash
        run: poetry install

      - name: [library] Build and Publish
        working-directory: library
        shell: bash
        run: poetry publish --build

      - name: [cli] Set fy-library version
        working-directory: cli
        shell: bash
        run: poetry add fy-library=="${{ inputs.FY_VERSION }}"

      - name: [cli] Install dependencies
        working-directory: cli
        shell: bash
        run: poetry install

      - name: [cli] Build and Publish
        working-directory: cli
        shell: bash
        run: poetry publish --build
