name: _Test Python Version

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: library
        shell: bash
        run: poetry install --with dev

      - name: Test
        shell: bash
        run: poetry run python -m unittest
        working-directory: library/tests

      - name: Install fy script
        shell: bash
        run: poetry install
        working-directory: cli

      - name: Regenerate Library
        shell: bash
        run: ../../fy.sh
        working-directory: library/src
